---
title: "Supervised Sentiment Analysis"
author: "Kathirmani Sukumar"
date: "March 2, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tm)
library(dplyr)
library(ggplot2)
library(wordcloud)
Sys.setenv(JAVA_HOME='C:/Program Files/Java/jre-9.0.4') # for 64-bit version
library(RWeka)
library(lsa)
library(lubridate)
hotstar = read.csv('e:/datasets/hotstar.allreviews_Sentiments.csv')
dim(hotstar)
View(hotstar)
```


```{r}

docs = VCorpus(VectorSource(na.omit(hotstar$Reviews)))
corpus_clean = tm_map(docs, content_transformer(tolower))

apply_regex = function (x) gsub('[^a-z ]', ' ', x)
corpus_clean = tm_map(corpus_clean, content_transformer(apply_regex))

custom_stop_words = c('got')
corpus_clean = tm_map(corpus_clean, removeWords, stopwords()) 
corpus_clean = tm_map(corpus_clean, removeWords, custom_stop_words)

dtm = DocumentTermMatrix(corpus_clean)
tdm = TermDocumentMatrix(corpus_clean)
df_dtm = as.data.frame(as.matrix(dtm))
df_tdm = as.data.frame(as.matrix(tdm))
dim(df_dtm)

```

## Train & Test Data
```{r}
bow = as.data.frame(sort(colSums(df_dtm), decreasing = T))
bow$words = rownames(bow)
names(bow) = c('Freq','words')
top_words = head(bow, 50)
View(top_words$words)
train = df_dtm[1:4000,top_words$words]
test = df_dtm[4001:5053,top_words$words]

library(tree)
train$sentiment = hotstar[1:4000,'Sentiment_Manual']
test$sentiment = hotstar[4001:5053,'Sentiment_Manual']

model = tree(sentiment~., data=train)

library(dplyr)
test$predict = predict(model, test %>% select(-sentiment), type='class')
table(test$sentiment, test$predict)
```


```{r}
sum(is.na(hotstar$Sentiment_Manual))
```

